import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import FirebaseProvider from '@/providers/FirebaseProvider';
import { ClerkProvider } from '@clerk/nextjs';
import NextUiProvider from '@/providers/NextUiProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <ClerkProvider>
         <html lang='en'>
            <body className={inter.className}>
               <FirebaseProvider>
                  <NextUiProvider>
                     <main className='max-w-2xl mx-auto'>{children}</main>
                  </NextUiProvider>
               </FirebaseProvider>
            </body>
         </html>
      </ClerkProvider>
   );
}
