import NavBar from '@/components/NavBar';
import FirebaseProvider from '@/providers/FirebaseProvider';
import Provider from '@/providers/NextSessionProvider';
import NextUiProvider from '@/providers/NextUiProvider';
import SubscriptionProvider from '@/providers/SubscriptionProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import SubscriptionModal from '@/components/subscriptions/SubscriptionModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'My Students Notes',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <Provider>
               <FirebaseProvider>
                  <NextUiProvider>
                     <SubscriptionProvider>
                        <main className='max-w-3xl mx-auto min-h-screen'>
                           <NavBar />
                           {children}
                           <Toaster />
                           <SubscriptionModal />
                        </main>
                     </SubscriptionProvider>
                  </NextUiProvider>
               </FirebaseProvider>
            </Provider>
         </body>
      </html>
   );
}
